/**
 * Names for the background sky.
 *
 * Three rules shape this file:
 *
 * 1. **Only real objects.** Every entry is a star that exists, under an
 *    identifier it actually carries. Nothing here is invented, which is why the
 *    list is finite and the starfield labels a subset of its points rather than
 *    all of them.
 * 2. **No repeats.** Finding the same star twice in one sky would read as a
 *    bug, so each hoverable point takes a distinct slot from this pool.
 * 3. **Familiar names first, and at least as many of them.** Proper names lead
 *    the tooltip and the catalogue list is capped at the length of the named
 *    list, so the sky answers with Kochab more often than with a survey number.
 *
 * Objects with several identifiers keep them all: Kepler-452 is also
 * KIC 8311864 and KOI-7016, and the tooltip shows the common name first.
 */

/** One object, as it is known across catalogues. */
export interface StarDesignation {
  /** The most familiar name. Shown first and largest. */
  readonly primary: string;
  /** Other identifiers for the same object, most familiar first. */
  readonly aliases: readonly string[];
}

/**
 * Objects with proper names and their catalogue identifiers.
 *
 * Names already used by the map itself are deliberately absent: a background
 * point called Vega beside the Vega waypoint would read as a mistake.
 */
const CURATED: readonly StarDesignation[] = [
  { primary: "Kepler-452", aliases: ["KIC 8311864", "KOI-7016"] },
  { primary: "Kepler-186", aliases: ["KIC 8120608", "KOI-571"] },
  { primary: "Kepler-22", aliases: ["KIC 10593626", "KOI-87"] },
  { primary: "Kepler-442", aliases: ["KIC 4138008", "KOI-4742"] },
  { primary: "Kepler-62", aliases: ["KIC 9002278", "KOI-701"] },
  { primary: "Kepler-16", aliases: ["KIC 12644769", "KOI-1611"] },
  { primary: "TRAPPIST-1", aliases: ["2MASS J23062928-0502285", "K2-112"] },
  { primary: "TOI-700", aliases: ["TIC 150428135", "2MASS J06282325-6534456"] },
  { primary: "K2-18", aliases: ["EPIC 201912552", "2MASS J11302370+0735178"] },
  { primary: "Helvetios", aliases: ["51 Pegasi", "HD 217014", "HIP 113357"] },
  { primary: "Copernicus", aliases: ["55 Cancri", "HD 75732", "HIP 43587"] },
  { primary: "Chalawan", aliases: ["47 Ursae Majoris", "HD 95128", "HIP 53721"] },
  { primary: "Lich", aliases: ["PSR B1257+12", "PSR J1300+1240"] },
  { primary: "Titawin", aliases: ["Upsilon Andromedae", "HD 9826", "HIP 7513"] },
  { primary: "Musica", aliases: ["18 Delphini", "HD 199665", "HIP 103527"] },
  { primary: "Libertas", aliases: ["Xi Aquilae", "HD 188310", "HIP 97938"] },
  { primary: "Barnard's Star", aliases: ["GJ 699", "HIP 87937"] },
  { primary: "Tau Ceti", aliases: ["HD 10700", "HIP 8102", "GJ 71"] },
  { primary: "Ran", aliases: ["Epsilon Eridani", "HD 22049", "HIP 16537"] },
  { primary: "Gliese 581", aliases: ["HO Librae", "HIP 74995"] },
  { primary: "Gliese 667 C", aliases: ["GJ 667 C", "HR 6426 C"] },
  { primary: "Wolf 359", aliases: ["CN Leonis", "GJ 406"] },
  { primary: "Ross 128", aliases: ["FI Virginis", "GJ 447"] },
  { primary: "Luyten's Star", aliases: ["GJ 273", "BD+05 1668"] },
  { primary: "Kapteyn's Star", aliases: ["GJ 191", "HD 33793"] },
  { primary: "Van Maanen's Star", aliases: ["GJ 35", "Wolf 28"] },
  { primary: "Teegarden's Star", aliases: ["SO J025300.5+165258", "GAT 1370"] },
  { primary: "HD 209458", aliases: ["V376 Pegasi", "HIP 108859"] },
  { primary: "HD 189733", aliases: ["V452 Vulpeculae", "HIP 98505"] },
  { primary: "KELT-9", aliases: ["HD 195689", "HIP 101360"] },
  { primary: "WASP-12", aliases: ["TYC 1891-27-1", "2MASS J06303327+2940202"] },
  { primary: "HAT-P-7", aliases: ["Kepler-2", "KIC 10666592"] },
  { primary: "Achernar", aliases: ["Alpha Eridani", "HD 10144", "HIP 7588"] },
  { primary: "Altair", aliases: ["Alpha Aquilae", "HD 187642", "HIP 97649"] },
  { primary: "Fomalhaut", aliases: ["Alpha Piscis Austrini", "HD 216956"] },
  { primary: "Capella", aliases: ["Alpha Aurigae", "HD 34029", "HIP 24608"] },
  { primary: "Procyon", aliases: ["Alpha Canis Minoris", "HD 61421"] },
  { primary: "Regulus", aliases: ["Alpha Leonis", "HD 87901", "HIP 49669"] },
  { primary: "Pollux", aliases: ["Beta Geminorum", "HD 62509", "HIP 37826"] },
  { primary: "Castor", aliases: ["Alpha Geminorum", "HD 60179"] },
  { primary: "Hadar", aliases: ["Beta Centauri", "Agena", "HD 122451"] },
  { primary: "Rigil Kentaurus", aliases: ["Alpha Centauri A", "HD 128620"] },
  { primary: "Toliman", aliases: ["Alpha Centauri B", "HD 128621"] },
  { primary: "Mimosa", aliases: ["Beta Crucis", "HD 111123"] },
  { primary: "Acrux", aliases: ["Alpha Crucis", "HD 108248"] },
  { primary: "Gacrux", aliases: ["Gamma Crucis", "HD 108903"] },
  { primary: "Shaula", aliases: ["Lambda Scorpii", "HD 158926"] },
  { primary: "Bellatrix", aliases: ["Gamma Orionis", "HD 35468"] },
  { primary: "Saiph", aliases: ["Kappa Orionis", "HD 38771"] },
  { primary: "Meissa", aliases: ["Lambda Orionis", "HD 36861"] },
  { primary: "Hatysa", aliases: ["Iota Orionis", "HD 37043"] },
  { primary: "Elnath", aliases: ["Beta Tauri", "HD 35497"] },
  { primary: "Alcyone", aliases: ["Eta Tauri", "HD 23630"] },
  { primary: "Merope", aliases: ["23 Tauri", "HD 23480"] },
  { primary: "Maia", aliases: ["20 Tauri", "HD 23408"] },
  { primary: "Electra", aliases: ["17 Tauri", "HD 23302"] },
  { primary: "Taygeta", aliases: ["19 Tauri", "HD 23338"] },
  { primary: "Atlas", aliases: ["27 Tauri", "HD 23850"] },
  { primary: "Pleione", aliases: ["28 Tauri", "HD 23862"] },
  { primary: "Denebola", aliases: ["Beta Leonis", "HD 102647"] },
  { primary: "Algieba", aliases: ["Gamma Leonis", "HD 89484"] },
  { primary: "Zosma", aliases: ["Delta Leonis", "HD 97603"] },
  { primary: "Algol", aliases: ["Beta Persei", "HD 19356"] },
  { primary: "Mirfak", aliases: ["Alpha Persei", "HD 20902"] },
  { primary: "Almach", aliases: ["Gamma Andromedae", "HD 12533"] },
  { primary: "Mirach", aliases: ["Beta Andromedae", "HD 6860"] },
  { primary: "Alpheratz", aliases: ["Alpha Andromedae", "Sirrah", "HD 358"] },
  { primary: "Hamal", aliases: ["Alpha Arietis", "HD 12929"] },
  { primary: "Sheratan", aliases: ["Beta Arietis", "HD 11636"] },
  { primary: "Diphda", aliases: ["Beta Ceti", "Deneb Kaitos", "HD 4128"] },
  { primary: "Menkar", aliases: ["Alpha Ceti", "HD 18884"] },
  { primary: "Mira", aliases: ["Omicron Ceti", "HD 14386"] },
  { primary: "Enif", aliases: ["Epsilon Pegasi", "HD 206778"] },
  { primary: "Markab", aliases: ["Alpha Pegasi", "HD 218045"] },
  { primary: "Scheat", aliases: ["Beta Pegasi", "HD 217906"] },
  { primary: "Algenib", aliases: ["Gamma Pegasi", "HD 886"] },
  { primary: "Sadalmelik", aliases: ["Alpha Aquarii", "HD 209750"] },
  { primary: "Sadalsuud", aliases: ["Beta Aquarii", "HD 204867"] },
  { primary: "Skat", aliases: ["Delta Aquarii", "HD 216627"] },
  { primary: "Nunki", aliases: ["Sigma Sagittarii", "HD 175191"] },
  { primary: "Kaus Australis", aliases: ["Epsilon Sagittarii", "HD 165024"] },
  { primary: "Rasalhague", aliases: ["Alpha Ophiuchi", "HD 159561"] },
  { primary: "Sabik", aliases: ["Eta Ophiuchi", "HD 155125"] },
  { primary: "Rasalgethi", aliases: ["Alpha Herculis", "HD 156014"] },
  { primary: "Kornephoros", aliases: ["Beta Herculis", "HD 148856"] },
  { primary: "Alphecca", aliases: ["Alpha Coronae Borealis", "Gemma", "HD 139006"] },
  { primary: "Muphrid", aliases: ["Eta Bootis", "HD 121370"] },
  { primary: "Izar", aliases: ["Epsilon Bootis", "HD 129989"] },
  { primary: "Seginus", aliases: ["Gamma Bootis", "HD 127762"] },
  { primary: "Cor Caroli", aliases: ["Alpha Canum Venaticorum", "HD 112413"] },
  { primary: "Dubhe", aliases: ["Alpha Ursae Majoris", "HD 95689"] },
  { primary: "Merak", aliases: ["Beta Ursae Majoris", "HD 95418"] },
  { primary: "Phecda", aliases: ["Gamma Ursae Majoris", "HD 103287"] },
  { primary: "Megrez", aliases: ["Delta Ursae Majoris", "HD 106591"] },
  { primary: "Alioth", aliases: ["Epsilon Ursae Majoris", "HD 112185"] },
  { primary: "Mizar", aliases: ["Zeta Ursae Majoris", "HD 116656"] },
  { primary: "Alcor", aliases: ["80 Ursae Majoris", "HD 116842"] },
  { primary: "Alkaid", aliases: ["Eta Ursae Majoris", "Benetnash", "HD 120315"] },
  { primary: "Kochab", aliases: ["Beta Ursae Minoris", "HD 131873"] },
  { primary: "Pherkad", aliases: ["Gamma Ursae Minoris", "HD 137422"] },
  { primary: "Yildun", aliases: ["Delta Ursae Minoris", "HD 166205"] },
  { primary: "Thuban", aliases: ["Alpha Draconis", "HD 123299"] },
  { primary: "Eltanin", aliases: ["Gamma Draconis", "HD 164058"] },
  { primary: "Rastaban", aliases: ["Beta Draconis", "HD 159181"] },
  { primary: "Schedar", aliases: ["Alpha Cassiopeiae", "HD 3712"] },
  { primary: "Caph", aliases: ["Beta Cassiopeiae", "HD 432"] },
  { primary: "Ruchbah", aliases: ["Delta Cassiopeiae", "HD 8538"] },
  { primary: "Segin", aliases: ["Epsilon Cassiopeiae", "HD 11415"] },
  { primary: "Alderamin", aliases: ["Alpha Cephei", "HD 203280"] },
  { primary: "Alfirk", aliases: ["Beta Cephei", "HD 205021"] },
  { primary: "Errai", aliases: ["Gamma Cephei", "HD 222404"] },
  { primary: "Sadr", aliases: ["Gamma Cygni", "HD 194093"] },
  { primary: "Albireo", aliases: ["Beta Cygni", "HD 183912"] },
  { primary: "Aljanah", aliases: ["Epsilon Cygni", "HD 197989"] },
  { primary: "Fawaris", aliases: ["Delta Cygni", "HD 186882"] },
  { primary: "Sheliak", aliases: ["Beta Lyrae", "HD 174638"] },
  { primary: "Sulafat", aliases: ["Gamma Lyrae", "HD 176437"] },
  { primary: "Tarazed", aliases: ["Gamma Aquilae", "HD 186791"] },
  { primary: "Alshain", aliases: ["Beta Aquilae", "HD 188512"] },
  { primary: "Rukbat", aliases: ["Alpha Sagittarii", "HD 174116"] },
  { primary: "Peacock", aliases: ["Alpha Pavonis", "HD 193924"] },
  { primary: "Atria", aliases: ["Alpha Trianguli Australis", "HD 150798"] },
  { primary: "Miaplacidus", aliases: ["Beta Carinae", "HD 80007"] },
  { primary: "Avior", aliases: ["Epsilon Carinae", "HD 71129"] },
  { primary: "Aspidiske", aliases: ["Iota Carinae", "HD 80404"] },
  { primary: "Suhail", aliases: ["Lambda Velorum", "HD 78647"] },
  { primary: "Alsephina", aliases: ["Delta Velorum", "HD 74956"] },
  { primary: "Markeb", aliases: ["Kappa Velorum", "HD 78764"] },
  { primary: "Naos", aliases: ["Zeta Puppis", "HD 66811"] },
  { primary: "Adhara", aliases: ["Epsilon Canis Majoris", "HD 52089"] },
  { primary: "Wezen", aliases: ["Delta Canis Majoris", "HD 54605"] },
  { primary: "Mirzam", aliases: ["Beta Canis Majoris", "HD 44743"] },
  { primary: "Aludra", aliases: ["Eta Canis Majoris", "HD 58350"] },
  { primary: "Furud", aliases: ["Zeta Canis Majoris", "HD 44402"] },
  { primary: "Gomeisa", aliases: ["Beta Canis Minoris", "HD 58715"] },
  { primary: "Alhena", aliases: ["Gamma Geminorum", "HD 47105"] },
  { primary: "Tejat", aliases: ["Mu Geminorum", "HD 44478"] },
  { primary: "Propus", aliases: ["Eta Geminorum", "HD 42995"] },
  { primary: "Mebsuta", aliases: ["Epsilon Geminorum", "HD 48329"] },
  { primary: "Wasat", aliases: ["Delta Geminorum", "HD 56986"] },
  { primary: "Alphard", aliases: ["Alpha Hydrae", "HD 81797"] },
  { primary: "Porrima", aliases: ["Gamma Virginis", "HD 110379"] },
  { primary: "Vindemiatrix", aliases: ["Epsilon Virginis", "HD 113226"] },
  { primary: "Heze", aliases: ["Zeta Virginis", "HD 118098"] },
  { primary: "Zubenelgenubi", aliases: ["Alpha Librae", "HD 130841"] },
  { primary: "Zubeneschamali", aliases: ["Beta Librae", "HD 135742"] },
  { primary: "Dschubba", aliases: ["Delta Scorpii", "HD 143275"] },
  { primary: "Acrab", aliases: ["Beta Scorpii", "HD 144217"] },
  { primary: "Larawag", aliases: ["Epsilon Scorpii", "HD 151680"] },
  { primary: "Sargas", aliases: ["Theta Scorpii", "HD 159532"] },
  { primary: "Lesath", aliases: ["Upsilon Scorpii", "HD 158408"] },
  { primary: "Unukalhai", aliases: ["Alpha Serpentis", "HD 140573"] },
  { primary: "Ankaa", aliases: ["Alpha Phoenicis", "HD 2261"] },
  { primary: "Alnair", aliases: ["Alpha Gruis", "HD 209952"] },
  { primary: "Tiaki", aliases: ["Beta Gruis", "HD 214952"] },
  { primary: "Diadem", aliases: ["Alpha Comae Berenices", "HD 114378"] },
  { primary: "Cursa", aliases: ["Beta Eridani", "HD 33111"] },
  { primary: "Zaurak", aliases: ["Gamma Eridani", "HD 25025"] },
  { primary: "Acamar", aliases: ["Theta Eridani", "HD 18622"] },
  { primary: "Keid", aliases: ["Omicron-2 Eridani", "40 Eridani", "HD 26965"] },
  { primary: "Arneb", aliases: ["Alpha Leporis", "HD 36673"] },
  { primary: "Nihal", aliases: ["Beta Leporis", "HD 36079"] },
  { primary: "Phact", aliases: ["Alpha Columbae", "HD 37795"] },
  { primary: "Wazn", aliases: ["Beta Columbae", "HD 39425"] },
  { primary: "Menkalinan", aliases: ["Beta Aurigae", "HD 40183"] },
  { primary: "Mahasim", aliases: ["Theta Aurigae", "HD 40312"] },
  { primary: "Hassaleh", aliases: ["Iota Aurigae", "HD 31398"] },
  { primary: "Almaaz", aliases: ["Epsilon Aurigae", "HD 31964"] },
  { primary: "Haedus", aliases: ["Eta Aurigae", "HD 32630"] },
  { primary: "Talitha", aliases: ["Iota Ursae Majoris", "HD 76644"] },
  { primary: "Muscida", aliases: ["Omicron Ursae Majoris", "HD 71369"] },
  { primary: "Tania Australis", aliases: ["Mu Ursae Majoris", "HD 89758"] },
  { primary: "Tania Borealis", aliases: ["Lambda Ursae Majoris", "HD 89021"] },
  { primary: "Alula Australis", aliases: ["Xi Ursae Majoris", "HD 98231"] },
  { primary: "Alula Borealis", aliases: ["Nu Ursae Majoris", "HD 98262"] },
  { primary: "Chara", aliases: ["Beta Canum Venaticorum", "HD 109358"] },
  { primary: "Nekkar", aliases: ["Beta Bootis", "HD 133208"] },
  { primary: "Alkalurops", aliases: ["Mu Bootis", "HD 137391"] },
  { primary: "Nusakan", aliases: ["Beta Coronae Borealis", "HD 137909"] },
  { primary: "Yed Prior", aliases: ["Delta Ophiuchi", "HD 146051"] },
  { primary: "Yed Posterior", aliases: ["Epsilon Ophiuchi", "HD 146791"] },
  { primary: "Cebalrai", aliases: ["Beta Ophiuchi", "HD 161096"] },
  { primary: "Marfik", aliases: ["Lambda Ophiuchi", "HD 148857"] },
  { primary: "Sinistra", aliases: ["Nu Ophiuchi", "HD 163917"] },
  { primary: "Alrescha", aliases: ["Alpha Piscium", "HD 12446"] },
  { primary: "Torcular", aliases: ["Omicron Piscium", "HD 10761"] },
  { primary: "Revati", aliases: ["Zeta Piscium", "HD 8556"] },
  { primary: "Baten Kaitos", aliases: ["Zeta Ceti", "HD 4581"] },
  { primary: "Kaffaljidhma", aliases: ["Gamma Ceti", "HD 16970"] },
  { primary: "Botein", aliases: ["Delta Arietis", "HD 19787"] },
  { primary: "Mesarthim", aliases: ["Gamma Arietis", "HD 11502"] },
  { primary: "Ain", aliases: ["Epsilon Tauri", "HD 28305"] },
  { primary: "Prima Hyadum", aliases: ["Gamma Tauri", "HD 27371"] },
  { primary: "Secunda Hyadum", aliases: ["Delta Tauri", "HD 27697"] },
  { primary: "Chertan", aliases: ["Theta Leonis", "HD 97633"] },
  { primary: "Subra", aliases: ["Omicron Leonis", "HD 83808"] },
  { primary: "Rasalas", aliases: ["Mu Leonis", "HD 85503"] },
  { primary: "Adhafera", aliases: ["Zeta Leonis", "HD 89025"] },
  { primary: "Alterf", aliases: ["Lambda Leonis", "HD 84441"] },
  { primary: "Praecipua", aliases: ["46 Leonis Minoris", "HD 94264"] },
  { primary: "Zavijava", aliases: ["Beta Virginis", "HD 102870"] },
  { primary: "Zaniah", aliases: ["Eta Virginis", "HD 107259"] },
  { primary: "Minelauva", aliases: ["Delta Virginis", "HD 112300"] },
  { primary: "Syrma", aliases: ["Iota Virginis", "HD 124850"] },
  { primary: "Kang", aliases: ["Kappa Virginis", "HD 124294"] },
  { primary: "Brachium", aliases: ["Sigma Librae", "HD 133216"] },
  { primary: "Alchiba", aliases: ["Alpha Corvi", "HD 105452"] },
  { primary: "Gienah", aliases: ["Gamma Corvi", "HD 106625"] },
  { primary: "Kraz", aliases: ["Beta Corvi", "HD 109379"] },
  { primary: "Algorab", aliases: ["Delta Corvi", "HD 108767"] },
  { primary: "Alkes", aliases: ["Alpha Crateris", "HD 95272"] },
  { primary: "Ashlesha", aliases: ["Epsilon Hydrae", "HD 74874"] },
  { primary: "Tureis", aliases: ["Rho Puppis", "HD 67523"] },
  { primary: "Azmidi", aliases: ["Xi Puppis", "HD 63700"] },
  { primary: "Tegmine", aliases: ["Zeta Cancri", "HD 68257"] },
  { primary: "Asellus Australis", aliases: ["Delta Cancri", "HD 74442"] },
  { primary: "Asellus Borealis", aliases: ["Gamma Cancri", "HD 74198"] },
  { primary: "Tarf", aliases: ["Beta Cancri", "HD 69267"] },
  { primary: "Meridiana", aliases: ["Alpha Coronae Australis", "HD 178253"] },
  { primary: "Okab", aliases: ["Zeta Aquilae", "HD 177724"] },
  { primary: "Terebellum", aliases: ["Omega Sagittarii", "HD 184124"] },
  { primary: "Albaldah", aliases: ["Pi Sagittarii", "HD 178524"] },
  { primary: "Ascella", aliases: ["Zeta Sagittarii", "HD 176687"] },
  { primary: "Kaus Media", aliases: ["Delta Sagittarii", "HD 168454"] },
  { primary: "Kaus Borealis", aliases: ["Lambda Sagittarii", "HD 169916"] },
  { primary: "Alnasl", aliases: ["Gamma Sagittarii", "Nash", "HD 165135"] },
  { primary: "Dabih", aliases: ["Beta Capricorni", "HD 194943"] },
  { primary: "Algedi", aliases: ["Alpha Capricorni", "HD 192947"] },
  { primary: "Nashira", aliases: ["Gamma Capricorni", "HD 206088"] },
  { primary: "Deneb Algedi", aliases: ["Delta Capricorni", "HD 207098"] },
  { primary: "Sadachbia", aliases: ["Gamma Aquarii", "HD 212061"] },
  { primary: "Situla", aliases: ["Kappa Aquarii", "HD 218452"] },
  { primary: "Ancha", aliases: ["Theta Aquarii", "HD 211391"] },
  { primary: "Homam", aliases: ["Zeta Pegasi", "HD 214923"] },
  { primary: "Matar", aliases: ["Eta Pegasi", "HD 215182"] },
  { primary: "Biham", aliases: ["Theta Pegasi", "HD 210418"] },
  { primary: "Salm", aliases: ["Tau Pegasi", "HD 220061"] },
  { primary: "Kitalpha", aliases: ["Alpha Equulei", "HD 202447"] },
  { primary: "Rotanev", aliases: ["Beta Delphini", "HD 196524"] },
  { primary: "Sualocin", aliases: ["Alpha Delphini", "HD 196867"] },
  { primary: "Aldulfin", aliases: ["Epsilon Delphini", "HD 195810"] },
  { primary: "Anser", aliases: ["Alpha Vulpeculae", "HD 183439"] },
  { primary: "Alya", aliases: ["Theta Serpentis", "HD 175638"] },
  { primary: "Giausar", aliases: ["Lambda Draconis", "HD 100029"] },
  { primary: "Edasich", aliases: ["Iota Draconis", "HD 137759"] },
  { primary: "Aldhibah", aliases: ["Zeta Draconis", "HD 155763"] },
  { primary: "Athebyne", aliases: ["Eta Draconis", "HD 148283"] },
  { primary: "Grumium", aliases: ["Xi Draconis", "HD 163588"] },
  { primary: "Altais", aliases: ["Delta Draconis", "HD 180711"] },
  { primary: "Alsafi", aliases: ["Sigma Draconis", "HD 185144"] },
  { primary: "Fafnir", aliases: ["42 Draconis", "HD 170693"] },
  { primary: "Alrakis", aliases: ["Mu Draconis", "HD 154906"] },
  { primary: "Kurhah", aliases: ["Xi Cephei", "HD 209790"] },
  { primary: "Garnet Star", aliases: ["Mu Cephei", "HD 206936"] },
  { primary: "Gliese 710", aliases: ["GJ 710", "HIP 89825"] },
  { primary: "61 Cygni", aliases: ["Bessel's Star", "GJ 820"] },
  { primary: "70 Ophiuchi", aliases: ["GJ 702", "HD 165341"] },
  { primary: "36 Ophiuchi", aliases: ["GJ 663", "HD 155886"] },
  { primary: "82 Eridani", aliases: ["HD 20794", "HIP 15510"] },
  { primary: "107 Piscium", aliases: ["GJ 68", "HD 10476"] },
  { primary: "Lalande 21185", aliases: ["GJ 411", "HD 95735"] },
  { primary: "Groombridge 34", aliases: ["GJ 15", "HD 1326"] },
  { primary: "Groombridge 1618", aliases: ["GJ 380", "HD 88230"] },
  { primary: "Struve 2398", aliases: ["GJ 725", "HD 173739"] },
  { primary: "Luyten 726-8", aliases: ["UV Ceti", "GJ 65"] },
  { primary: "Wolf 1061", aliases: ["GJ 628", "HIP 80824"] },
  { primary: "Wolf 424", aliases: ["GJ 473", "FL Virginis"] },
  { primary: "Ross 248", aliases: ["GJ 905", "HH Andromedae"] },
  { primary: "Ross 614", aliases: ["GJ 234", "V577 Monocerotis"] },
  { primary: "Lacaille 9352", aliases: ["GJ 887", "HD 217987"] },
  { primary: "Lacaille 8760", aliases: ["GJ 825", "AX Microscopii"] },
  { primary: "Delta Pavonis", aliases: ["GJ 780", "HD 190248"] },
  { primary: "Beta Hydri", aliases: ["HD 2151", "HIP 2021"] },
  { primary: "Zeta Tucanae", aliases: ["HD 1581", "HIP 1599"] },
  { primary: "Chi1 Orionis", aliases: ["GJ 222", "HD 39587"] },
  { primary: "Gamma Leporis", aliases: ["HD 38393", "HIP 27072"] },
  { primary: "Xi Bootis", aliases: ["GJ 566", "HD 131156"] },
  { primary: "Sigma Bootis", aliases: ["HD 128167", "HIP 71284"] },
  { primary: "Mu Cassiopeiae", aliases: ["HD 6582", "HIP 5336"] },
  { primary: "Achird", aliases: ["Eta Cassiopeiae", "HD 4614"] },
  { primary: "Zeta Herculis", aliases: ["HD 150680", "HIP 81693"] },
  { primary: "Mu Herculis", aliases: ["HD 161797", "HIP 86974"] },
  { primary: "Beta Comae Berenices", aliases: ["HD 114710", "HIP 64394"] },
  { primary: "Delta Cephei", aliases: ["HD 213306", "HIP 110991"] },
  { primary: "Eta Aquilae", aliases: ["HD 187929", "HIP 97804"] },
  { primary: "Mekbuda", aliases: ["Zeta Geminorum", "HD 52973"] },
  { primary: "RR Lyrae", aliases: ["HD 182989", "HIP 95497"] },
  { primary: "Chi Cygni", aliases: ["HD 187796", "HIP 97629"] },
  { primary: "R Leonis", aliases: ["HD 84748", "HIP 48036"] },
  { primary: "R Doradus", aliases: ["HD 29712", "HIP 21479"] },
  { primary: "L2 Puppis", aliases: ["HD 56096", "HIP 34922"] },
  { primary: "T Tauri", aliases: ["HD 284419", "HBC 35"] },
  { primary: "FU Orionis", aliases: ["HBC 76", "IRAS 05426+0903"] },
  { primary: "AB Aurigae", aliases: ["HD 31293", "HIP 22910"] },
  { primary: "Beta Pictoris", aliases: ["HD 39060", "HIP 27321"] },
  { primary: "AU Microscopii", aliases: ["GJ 803", "HD 197481"] },
  { primary: "TW Hydrae", aliases: ["HIP 53911", "CD-34 7151"] },
  { primary: "Eta Carinae", aliases: ["HD 93308", "HR 4210"] },
  { primary: "P Cygni", aliases: ["34 Cygni", "HD 193237"] },
  { primary: "VY Canis Majoris", aliases: ["HD 58061", "HIP 35793"] },
  { primary: "UY Scuti", aliases: ["BD-12 5055", "IRC -10422"] },
  { primary: "Rho Cassiopeiae", aliases: ["HD 224014", "HIP 117863"] },
  { primary: "S Doradus", aliases: ["HD 35343", "HIP 25336"] },
  { primary: "WR 104", aliases: ["Ve 2-45", "IRAS 18024-2333"] },
  { primary: "WR 124", aliases: ["Merrill's Star", "HD 192163"] },
  { primary: "Plaskett's Star", aliases: ["HD 47129", "HIP 31473"] },
  { primary: "Zeta Ophiuchi", aliases: ["HD 149757", "HIP 81377"] },
  { primary: "Theta1 Orionis C", aliases: ["HD 37022", "Trapezium C"] },
  { primary: "Sigma Orionis", aliases: ["HD 37468", "HIP 26549"] },
  { primary: "Regor", aliases: ["Gamma Velorum", "HD 68273"] },
  { primary: "Delta Scuti", aliases: ["HD 172748", "HIP 91726"] },
  { primary: "Sirius B", aliases: ["Alpha Canis Majoris B", "The Pup"] },
  { primary: "Procyon B", aliases: ["Alpha Canis Minoris B", "HD 61421 B"] },
  { primary: "Stein 2051 B", aliases: ["GJ 169.1 B", "LHS 26 B"] },
  { primary: "Van Biesbroeck 8", aliases: ["VB 8", "GJ 644 C"] },
  { primary: "Van Biesbroeck 10", aliases: ["VB 10", "GJ 752 B"] },
  { primary: "Kruger 60", aliases: ["GJ 860", "DO Cephei"] },
  { primary: "Scholz's Star", aliases: ["WISE 0720-0846", "2MASS J07200325-0846499"] },
  { primary: "Luhman 16", aliases: ["WISE 1049-5319", "DENIS J104814.6-395606"] },
  { primary: "Gliese 229", aliases: ["GJ 229", "HD 42581"] },
  { primary: "Gliese 570", aliases: ["GJ 570", "HD 131977"] },
  { primary: "Gliese 876", aliases: ["GJ 876", "IL Aquarii"] },
  { primary: "Gliese 436", aliases: ["GJ 436", "LHS 310"] },
  { primary: "Gliese 1214", aliases: ["GJ 1214", "LHS 3275"] },
  { primary: "Gliese 1132", aliases: ["GJ 1132", "LHS 3417"] },
  { primary: "Gliese 357", aliases: ["GJ 357", "LHS 2157"] },
  { primary: "Gliese 486", aliases: ["GJ 486", "LHS 2455"] },
  { primary: "Gliese 687", aliases: ["GJ 687", "LHS 450"] },
  { primary: "Gliese 674", aliases: ["GJ 674", "LHS 449"] },
  { primary: "Gliese 682", aliases: ["GJ 682", "LHS 451"] },
  { primary: "Gliese 832", aliases: ["GJ 832", "LHS 3707"] },
  { primary: "Gliese 1002", aliases: ["GJ 1002", "LHS 2"] },
  { primary: "Gliese 3323", aliases: ["GJ 3323", "LHS 1723"] },
  { primary: "LHS 1140", aliases: ["GJ 3053", "LP 731-58"] },
  { primary: "LHS 3844", aliases: ["TIC 410153553"] },
  { primary: "Zubenelhakrabi", aliases: ["Gamma Librae", "HD 138905"] },
  { primary: "Mothallah", aliases: ["Alpha Trianguli", "HD 11443"] },
  { primary: "Alsciaukat", aliases: ["31 Lyncis", "HD 70272"] },
  { primary: "Alkaphrah", aliases: ["Kappa Ursae Majoris", "HD 77327"] },
  { primary: "Beemim", aliases: ["Upsilon3 Eridani", "HD 27861"] },
  { primary: "Theemin", aliases: ["Upsilon2 Eridani", "HD 28028"] },
  { primary: "Sceptrum", aliases: ["53 Eridani", "HD 29503"] },
  { primary: "Jishui", aliases: ["Omicron Geminorum", "HD 61110"] },
  { primary: "Marsic", aliases: ["Kappa Herculis", "HD 145001"] },
  { primary: "Maasym", aliases: ["Lambda Herculis", "HD 158899"] },
  { primary: "Cujam", aliases: ["Omega Herculis", "HD 148112"] },
  { primary: "Sarin", aliases: ["Delta Herculis", "HD 156164"] },
  { primary: "Misam", aliases: ["Kappa Persei", "HD 19476"] },
  { primary: "Atik", aliases: ["Omicron Persei", "HD 23180"] },
  { primary: "Menkib", aliases: ["Xi Persei", "HD 24912"] },
  { primary: "Miram", aliases: ["Eta Persei", "HD 17506"] },
  { primary: "Muliphein", aliases: ["Gamma Canis Majoris", "HD 46328"] },
  { primary: "Unurgunite", aliases: ["Sigma Canis Majoris", "HD 52877"] },
  { primary: "Aldhanab", aliases: ["Gamma Gruis", "HD 209688"] },
  { primary: "Piautos", aliases: ["Lambda Cancri", "HD 65759"] },
  { primary: "Nahn", aliases: ["Xi Cancri", "HD 73900"] },
  { primary: "Meleph", aliases: ["Epsilon Cancri", "HD 73731"] },
  { primary: "Tianguan", aliases: ["Zeta Tauri", "HD 37202"] },
  { primary: "Fuyue", aliases: ["G Scorpii", "HD 161892"] },
  { primary: "Ginan", aliases: ["Epsilon Crucis", "HD 107446"] },
  { primary: "Imai", aliases: ["Delta Crucis", "HD 106490"] },
  { primary: "Pipirima", aliases: ["Mu2 Scorpii", "HD 151985"] },
  { primary: "Xamidimura", aliases: ["Mu1 Scorpii", "HD 151890"] },
  { primary: "Iklil", aliases: ["Rho Scorpii", "HD 142669"] },
  { primary: "Jabbah", aliases: ["Nu Scorpii", "HD 145502"] },
  { primary: "Paikauhale", aliases: ["Tau Scorpii", "HD 149438"] },
  { primary: "Alniyat", aliases: ["Sigma Scorpii", "HD 147165"] },
  { primary: "Fang", aliases: ["Pi Scorpii", "HD 143018"] },
  { primary: "Girtab", aliases: ["Kappa Scorpii", "HD 160578"] },
  { primary: "Polis", aliases: ["Mu Sagittarii", "HD 166937"] },
  { primary: "Arkab Prior", aliases: ["Beta1 Sagittarii", "HD 181454"] },
  { primary: "Arkab Posterior", aliases: ["Beta2 Sagittarii", "HD 181623"] },
  { primary: "Sadalbari", aliases: ["Mu Pegasi", "HD 216131"] },
  { primary: "Sham", aliases: ["Alpha Sagittae", "HD 185758"] },
  { primary: "Alsahm", aliases: ["Gamma Sagittae", "HD 189319"] },
  { primary: "Azelfafage", aliases: ["Pi1 Cygni", "HD 206672"] },
  { primary: "Ruchba", aliases: ["Omega Cygni", "HD 189962"] },
  { primary: "Gienah Cygni", aliases: [] },
  { primary: "Taiyangshou", aliases: ["Chi Ursae Majoris", "HD 102224"] },
  { primary: "Merga", aliases: ["38 Bootis", "HD 129153"] },
  { primary: "Xuange", aliases: ["Lambda Bootis", "HD 125162"] },
] as const;

/**
 * Catalogue designations.
 *
 * Real identifiers from real surveys, listed rather than generated: an invented
 * catalogue number would be a small lie printed over the sky. The list is
 * capped at the length of the named list above, so hovering the sky turns up a
 * familiar name at least as often as a survey number.
 */
const CATALOGUED: readonly StarDesignation[] = [
  { primary: "Kepler-4", aliases: [] },
  { primary: "K2-3", aliases: [] },
  { primary: "TOI-125", aliases: [] },
  { primary: "WASP-1", aliases: [] },
  { primary: "HAT-P-1", aliases: [] },
  { primary: "Gliese 1", aliases: ["GJ 1"] },
  { primary: "HD 1461", aliases: [] },
  { primary: "Kepler-5", aliases: [] },
  { primary: "K2-9", aliases: [] },
  { primary: "TOI-172", aliases: [] },
  { primary: "WASP-4", aliases: [] },
  { primary: "HAT-P-2", aliases: [] },
  { primary: "Gliese 15", aliases: [] },
  { primary: "HD 3651", aliases: [] },
  { primary: "Kepler-6", aliases: [] },
  { primary: "TOI-178", aliases: [] },
  { primary: "WASP-6", aliases: [] },
  { primary: "HAT-P-3", aliases: [] },
  { primary: "Gliese 27", aliases: ["GJ 27"] },
  { primary: "HD 4308", aliases: [] },
  { primary: "Kepler-7", aliases: [] },
  { primary: "K2-21", aliases: [] },
  { primary: "TOI-181", aliases: [] },
  { primary: "WASP-7", aliases: [] },
  { primary: "HAT-P-5", aliases: [] },
  { primary: "Gliese 48", aliases: ["GJ 48"] },
  { primary: "HD 7924", aliases: [] },
  { primary: "Kepler-8", aliases: [] },
  { primary: "K2-22", aliases: [] },
  { primary: "TOI-216", aliases: [] },
  { primary: "HAT-P-6", aliases: [] },
  { primary: "Gliese 54", aliases: ["GJ 54"] },
  { primary: "HD 10180", aliases: [] },
  { primary: "Kepler-9", aliases: [] },
  { primary: "K2-24", aliases: [] },
  { primary: "TOI-237", aliases: [] },
  { primary: "WASP-14", aliases: [] },
  { primary: "Gliese 83", aliases: ["GJ 83"] },
  { primary: "HD 10647", aliases: [] },
  { primary: "Kepler-10", aliases: [] },
  { primary: "K2-25", aliases: [] },
  { primary: "TOI-251", aliases: [] },
  { primary: "WASP-15", aliases: [] },
  { primary: "HAT-P-8", aliases: [] },
  { primary: "Gliese 96", aliases: ["GJ 96"] },
  { primary: "Kepler-11", aliases: [] },
  { primary: "K2-26", aliases: [] },
  { primary: "TOI-260", aliases: [] },
  { primary: "WASP-17", aliases: [] },
  { primary: "HAT-P-9", aliases: [] },
  { primary: "Gliese 105", aliases: ["GJ 105"] },
  { primary: "HD 20003", aliases: [] },
  { primary: "Kepler-12", aliases: [] },
  { primary: "K2-28", aliases: [] },
  { primary: "TOI-270", aliases: [] },
  { primary: "WASP-18", aliases: [] },
  { primary: "HAT-P-11", aliases: [] },
  { primary: "Gliese 109", aliases: ["GJ 109"] },
  { primary: "Kepler-14", aliases: [] },
  { primary: "K2-33", aliases: [] },
  { primary: "TOI-402", aliases: [] },
  { primary: "WASP-19", aliases: [] },
  { primary: "HAT-P-12", aliases: [] },
  { primary: "Gliese 117", aliases: ["GJ 117"] },
  { primary: "Kepler-15", aliases: [] },
  { primary: "K2-36", aliases: [] },
  { primary: "TOI-421", aliases: [] },
  { primary: "WASP-22", aliases: [] },
  { primary: "HAT-P-13", aliases: [] },
  { primary: "Gliese 133", aliases: ["GJ 133"] },
  { primary: "HD 23079", aliases: [] },
  { primary: "K2-38", aliases: [] },
  { primary: "TOI-431", aliases: [] },
  { primary: "WASP-26", aliases: [] },
  { primary: "HAT-P-14", aliases: [] },
  { primary: "Gliese 143", aliases: ["GJ 143"] },
  { primary: "Kepler-17", aliases: [] },
  { primary: "K2-39", aliases: [] },
  { primary: "TOI-469", aliases: [] },
  { primary: "WASP-29", aliases: [] },
  { primary: "HAT-P-15", aliases: [] },
  { primary: "Gliese 156", aliases: ["GJ 156"] },
  { primary: "HD 27442", aliases: [] },
  { primary: "Kepler-18", aliases: [] },
  { primary: "K2-44", aliases: [] },
  { primary: "TOI-500", aliases: [] },
  { primary: "WASP-31", aliases: [] },
  { primary: "HAT-P-16", aliases: [] },
  { primary: "Gliese 160", aliases: ["GJ 160"] },
  { primary: "HD 28185", aliases: [] },
  { primary: "Kepler-19", aliases: [] },
  { primary: "K2-55", aliases: [] },
  { primary: "TOI-540", aliases: [] },
  { primary: "WASP-33", aliases: [] },
  { primary: "HAT-P-17", aliases: [] },
  { primary: "Gliese 163", aliases: ["GJ 163"] },
  { primary: "HD 33564", aliases: [] },
  { primary: "Kepler-20", aliases: [] },
  { primary: "K2-60", aliases: [] },
  { primary: "TOI-544", aliases: [] },
  { primary: "WASP-39", aliases: [] },
  { primary: "HAT-P-18", aliases: [] },
  { primary: "Gliese 173", aliases: ["GJ 173"] },
  { primary: "HD 37124", aliases: [] },
  { primary: "Kepler-21", aliases: [] },
  { primary: "K2-66", aliases: [] },
  { primary: "TOI-561", aliases: [] },
  { primary: "WASP-43", aliases: [] },
  { primary: "HAT-P-19", aliases: [] },
  { primary: "Gliese 176", aliases: ["GJ 176"] },
  { primary: "HD 38529", aliases: [] },
  { primary: "Kepler-23", aliases: [] },
  { primary: "K2-72", aliases: [] },
  { primary: "TOI-620", aliases: [] },
  { primary: "WASP-47", aliases: [] },
  { primary: "HAT-P-20", aliases: [] },
  { primary: "Gliese 179", aliases: ["GJ 179"] },
  { primary: "HD 39091", aliases: [] },
  { primary: "Kepler-25", aliases: [] },
  { primary: "K2-77", aliases: [] },
  { primary: "TOI-674", aliases: [] },
  { primary: "WASP-49", aliases: [] },
  { primary: "HAT-P-22", aliases: [] },
  { primary: "Gliese 180", aliases: ["GJ 180"] },
  { primary: "HD 40307", aliases: [] },
  { primary: "Kepler-26", aliases: [] },
  { primary: "K2-79", aliases: [] },
  { primary: "TOI-677", aliases: [] },
  { primary: "WASP-52", aliases: [] },
  { primary: "HAT-P-23", aliases: [] },
  { primary: "Gliese 191", aliases: [] },
  { primary: "HD 41004", aliases: [] },
  { primary: "Kepler-30", aliases: [] },
  { primary: "K2-87", aliases: [] },
  { primary: "WASP-62", aliases: [] },
  { primary: "HAT-P-24", aliases: [] },
  { primary: "Gliese 205", aliases: ["GJ 205"] },
  { primary: "HD 45350", aliases: [] },
  { primary: "Kepler-32", aliases: [] },
  { primary: "K2-90", aliases: [] },
  { primary: "TOI-763", aliases: [] },
  { primary: "WASP-63", aliases: [] },
  { primary: "HAT-P-26", aliases: [] },
  { primary: "Gliese 213", aliases: ["GJ 213"] },
  { primary: "HD 47186", aliases: [] },
  { primary: "Kepler-33", aliases: [] },
  { primary: "K2-93", aliases: [] },
  { primary: "TOI-776", aliases: [] },
  { primary: "WASP-69", aliases: [] },
  { primary: "HAT-P-27", aliases: [] },
  { primary: "Gliese 231", aliases: ["GJ 231"] },
  { primary: "HD 50554", aliases: [] },
  { primary: "Kepler-34", aliases: [] },
  { primary: "K2-95", aliases: [] },
  { primary: "TOI-813", aliases: [] },
  { primary: "WASP-74", aliases: [] },
  { primary: "HAT-P-28", aliases: [] },
  { primary: "Gliese 250", aliases: ["GJ 250"] },
  { primary: "HD 52265", aliases: [] },
  { primary: "Kepler-35", aliases: [] },
  { primary: "K2-100", aliases: [] },
  { primary: "TOI-824", aliases: [] },
  { primary: "WASP-76", aliases: [] },
  { primary: "HAT-P-30", aliases: [] },
  { primary: "Gliese 264", aliases: ["GJ 264"] },
  { primary: "HD 60532", aliases: [] },
  { primary: "Kepler-36", aliases: [] },
  { primary: "K2-106", aliases: [] },
  { primary: "TOI-833", aliases: [] },
  { primary: "WASP-79", aliases: [] },
  { primary: "HAT-P-32", aliases: [] },
  { primary: "Gliese 273", aliases: [] },
  { primary: "Kepler-37", aliases: [] },
  { primary: "K2-110", aliases: [] },
  { primary: "TOI-837", aliases: [] },
  { primary: "WASP-80", aliases: [] },
  { primary: "HAT-P-33", aliases: [] },
  { primary: "Gliese 300", aliases: ["GJ 300"] },
  { primary: "HD 69830", aliases: [] },
  { primary: "Kepler-38", aliases: [] },
  { primary: "K2-114", aliases: [] },
  { primary: "TOI-849", aliases: [] },
  { primary: "WASP-84", aliases: [] },
  { primary: "HAT-P-36", aliases: [] },
  { primary: "Gliese 317", aliases: ["GJ 317"] },
  { primary: "HD 70642", aliases: [] },
  { primary: "Kepler-39", aliases: [] },
  { primary: "K2-116", aliases: [] },
  { primary: "TOI-892", aliases: [] },
  { primary: "WASP-96", aliases: [] },
  { primary: "HAT-P-38", aliases: [] },
  { primary: "Gliese 328", aliases: ["GJ 328"] },
  { primary: "HD 72659", aliases: [] },
  { primary: "Kepler-40", aliases: [] },
  { primary: "K2-121", aliases: [] },
  { primary: "TOI-942", aliases: [] },
  { primary: "WASP-100", aliases: [] },
  { primary: "HAT-P-41", aliases: [] },
  { primary: "Gliese 338", aliases: ["GJ 338"] },
  { primary: "HD 73256", aliases: [] },
  { primary: "Kepler-42", aliases: [] },
  { primary: "K2-129", aliases: [] },
  { primary: "TOI-1064", aliases: [] },
  { primary: "WASP-103", aliases: [] },
  { primary: "HAT-P-44", aliases: [] },
  { primary: "Gliese 361", aliases: ["GJ 361"] },
  { primary: "HD 73534", aliases: [] },
  { primary: "Kepler-43", aliases: [] },
  { primary: "K2-133", aliases: [] },
  { primary: "TOI-1075", aliases: [] },
  { primary: "WASP-107", aliases: [] },
  { primary: "HAT-P-46", aliases: [] },
  { primary: "Gliese 367", aliases: ["GJ 367"] },
  { primary: "HD 75898", aliases: [] },
  { primary: "Kepler-45", aliases: [] },
  { primary: "K2-136", aliases: [] },
  { primary: "TOI-1130", aliases: [] },
  { primary: "WASP-110", aliases: [] },
  { primary: "HAT-P-49", aliases: [] },
  { primary: "Gliese 378", aliases: ["GJ 378"] },
  { primary: "HD 76700", aliases: [] },
  { primary: "Kepler-47", aliases: [] },
  { primary: "K2-138", aliases: [] },
  { primary: "TOI-1136", aliases: [] },
  { primary: "WASP-117", aliases: [] },
  { primary: "HAT-P-51", aliases: [] },
  { primary: "Gliese 382", aliases: ["GJ 382"] },
  { primary: "HD 80606", aliases: [] },
  { primary: "Kepler-48", aliases: [] },
  { primary: "K2-141", aliases: [] },
  { primary: "TOI-1201", aliases: [] },
  { primary: "WASP-121", aliases: [] },
  { primary: "HAT-P-54", aliases: [] },
  { primary: "Gliese 393", aliases: ["GJ 393"] },
  { primary: "HD 82943", aliases: [] },
  { primary: "Kepler-51", aliases: [] },
  { primary: "K2-146", aliases: [] },
  { primary: "TOI-1231", aliases: [] },
  { primary: "WASP-127", aliases: [] },
  { primary: "HAT-P-57", aliases: [] },
  { primary: "Gliese 402", aliases: ["GJ 402"] },
  { primary: "HD 85512", aliases: [] },
  { primary: "Kepler-56", aliases: [] },
  { primary: "K2-155", aliases: [] },
  { primary: "TOI-1233", aliases: [] },
  { primary: "WASP-132", aliases: [] },
  { primary: "HAT-P-65", aliases: [] },
  { primary: "Gliese 408", aliases: ["GJ 408"] },
  { primary: "HD 89744", aliases: [] },
  { primary: "Kepler-60", aliases: [] },
  { primary: "K2-165", aliases: [] },
  { primary: "TOI-1266", aliases: [] },
  { primary: "WASP-141", aliases: [] },
  { primary: "HAT-P-67", aliases: [] },
  { primary: "Gliese 414", aliases: ["GJ 414"] },
  { primary: "HD 92788", aliases: [] },
  { primary: "K2-174", aliases: [] },
  { primary: "TOI-1338", aliases: [] },
  { primary: "WASP-145", aliases: [] },
  { primary: "HAT-P-70", aliases: [] },
  { primary: "Gliese 424", aliases: ["GJ 424"] },
  { primary: "HD 93083", aliases: [] },
  { primary: "Kepler-68", aliases: [] },
  { primary: "K2-180", aliases: [] },
  { primary: "TOI-1410", aliases: [] },
  { primary: "WASP-166", aliases: [] },
  { primary: "Gliese 433", aliases: ["GJ 433"] },
  { primary: "HD 95089", aliases: [] },
  { primary: "Kepler-69", aliases: [] },
  { primary: "K2-183", aliases: [] },
  { primary: "TOI-1431", aliases: [] },
  { primary: "WASP-178", aliases: [] },
  { primary: "Gliese 445", aliases: ["GJ 445"] },
  { primary: "HD 99492", aliases: [] },
  { primary: "Kepler-70", aliases: [] },
  { primary: "K2-187", aliases: [] },
  { primary: "TOI-1442", aliases: [] },
  { primary: "WASP-189", aliases: [] },
  { primary: "Gliese 458", aliases: ["GJ 458"] },
  { primary: "HD 100777", aliases: [] },
  { primary: "Kepler-78", aliases: [] },
  { primary: "K2-190", aliases: [] },
  { primary: "TOI-1452", aliases: [] },
  { primary: "Gliese 465", aliases: ["GJ 465"] },
  { primary: "HD 102117", aliases: [] },
  { primary: "Kepler-80", aliases: [] },
  { primary: "K2-198", aliases: [] },
  { primary: "TOI-1468", aliases: [] },
  { primary: "Gliese 480", aliases: ["GJ 480"] },
  { primary: "HD 104067", aliases: [] },
  { primary: "Kepler-84", aliases: [] },
  { primary: "K2-201", aliases: [] },
  { primary: "TOI-1518", aliases: [] },
  { primary: "Gliese 494", aliases: ["GJ 494"] },
  { primary: "HD 106252", aliases: [] },
  { primary: "Kepler-88", aliases: [] },
  { primary: "K2-212", aliases: [] },
  { primary: "TOI-1601", aliases: [] },
  { primary: "Gliese 508", aliases: ["GJ 508"] },
  { primary: "HD 108874", aliases: [] },
  { primary: "Kepler-89", aliases: [] },
  { primary: "K2-216", aliases: [] },
  { primary: "TOI-1685", aliases: [] },
  { primary: "Gliese 514", aliases: ["GJ 514"] },
  { primary: "HD 111232", aliases: [] },
  { primary: "Kepler-90", aliases: [] },
  { primary: "K2-222", aliases: [] },
  { primary: "TOI-1693", aliases: [] },
  { primary: "Gliese 526", aliases: ["GJ 526"] },
  { primary: "HD 114386", aliases: [] },
  { primary: "Kepler-93", aliases: [] },
  { primary: "K2-229", aliases: [] },
  { primary: "TOI-1728", aliases: [] },
  { primary: "Gliese 536", aliases: ["GJ 536"] },
  { primary: "HD 114729", aliases: [] },
  { primary: "Kepler-94", aliases: [] },
  { primary: "K2-233", aliases: [] },
  { primary: "TOI-1759", aliases: [] },
  { primary: "Gliese 555", aliases: ["GJ 555"] },
  { primary: "HD 117207", aliases: [] },
  { primary: "Kepler-95", aliases: [] },
  { primary: "K2-236", aliases: [] },
  { primary: "TOI-1789", aliases: [] },
  { primary: "Gliese 569", aliases: ["GJ 569"] },
  { primary: "HD 117618", aliases: [] },
  { primary: "Kepler-96", aliases: [] },
  { primary: "K2-239", aliases: [] },
  { primary: "TOI-1798", aliases: [] },
  { primary: "HD 121504", aliases: [] },
  { primary: "Kepler-97", aliases: [] },
  { primary: "K2-240", aliases: [] },
  { primary: "TOI-1807", aliases: [] },
  { primary: "Gliese 588", aliases: ["GJ 588"] },
  { primary: "HD 128311", aliases: [] },
  { primary: "Kepler-98", aliases: [] },
  { primary: "K2-250", aliases: [] },
  { primary: "TOI-1824", aliases: [] },
  { primary: "Gliese 606", aliases: ["GJ 606"] },
  { primary: "HD 130322", aliases: [] },
  { primary: "Kepler-99", aliases: [] },
  { primary: "K2-257", aliases: [] },
  { primary: "TOI-1853", aliases: [] },
  { primary: "Gliese 618", aliases: ["GJ 618"] },
  { primary: "HD 134987", aliases: [] },
  { primary: "Kepler-100", aliases: [] },
  { primary: "K2-265", aliases: [] },
  { primary: "TOI-2000", aliases: [] },
  { primary: "Gliese 625", aliases: ["GJ 625"] },
  { primary: "HD 136118", aliases: [] },
  { primary: "Kepler-102", aliases: [] },
  { primary: "K2-269", aliases: [] },
  { primary: "TOI-2076", aliases: [] },
  { primary: "Gliese 649", aliases: ["GJ 649"] },
  { primary: "HD 141937", aliases: [] },
  { primary: "Kepler-106", aliases: [] },
  { primary: "K2-274", aliases: [] },
  { primary: "TOI-2109", aliases: [] },
  { primary: "Gliese 654", aliases: ["GJ 654"] },
  { primary: "HD 142415", aliases: [] },
  { primary: "Kepler-107", aliases: [] },
  { primary: "K2-280", aliases: [] },
  { primary: "TOI-2134", aliases: [] },
  { primary: "Gliese 667", aliases: ["GJ 667"] },
  { primary: "HD 145377", aliases: [] },
  { primary: "Kepler-108", aliases: [] },
  { primary: "K2-285", aliases: [] },
  { primary: "TOI-2180", aliases: [] },
  { primary: "Gliese 671", aliases: ["GJ 671"] },
  { primary: "HD 147018", aliases: [] },
  { primary: "Kepler-109", aliases: [] },
  { primary: "K2-291", aliases: [] },
  { primary: "TOI-2260", aliases: [] },
  { primary: "Gliese 686", aliases: ["GJ 686"] },
  { primary: "HD 148156", aliases: [] },
  { primary: "Kepler-110", aliases: [] },
  { primary: "K2-295", aliases: [] },
] as const;

/** Everything a background star can be called. */
const POOL: readonly StarDesignation[] = [...CURATED, ...CATALOGUED];

/**
 * How many points the sky can label without repeating itself. The starfield
 * makes exactly this many of its points hoverable.
 */
export const SKY_DESIGNATION_COUNT = POOL.length;

/**
 * Deterministic shuffle, so neighbouring points in a buffer do not end up with
 * neighbouring entries from the list, and so named stars and catalogue numbers
 * are mixed evenly across the sky. Fixed seed: the sky reads the same on every
 * visit.
 */
const ORDER: readonly number[] = (() => {
  const order = POOL.map((_, index) => index);
  let seed = 0x9e3779b9;
  for (let index = order.length - 1; index > 0; index -= 1) {
    seed = (seed * 1664525 + 1013904223) >>> 0;
    const swap = seed % (index + 1);
    const held = order[index];
    order[index] = order[swap];
    order[swap] = held;
  }
  return order;
})();

/**
 * The designation for a point's slot.
 *
 * One slot per hoverable point, never more slots than the pool holds, so no two
 * points can carry the same name.
 */
export function designationForSlot(slot: number): StarDesignation | null {
  if (slot < 0 || slot >= ORDER.length) return null;
  return POOL[ORDER[slot]];
}
